[features]
seeds = false
[programs.localnet]
jun_v0 = "7Yo9DesUhQnAVjzwsL6NX2CEpa1c5gTEn47bqaMYa5eP"

[programs.devnet]
jun_v0 = "7Yo9DesUhQnAVjzwsL6NX2CEpa1c5gTEn47bqaMYa5eP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
